# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false # Ensure that we always redirect